### ISSUE TITLE
Check if value is null

### ISSUE THREAD

**Issue by Loomeh** [Wins1ey/LinuxAutoSplitter#16]
Sorry for contacting this you way, I'm in school and I had a eureka moment and I don't have access to Discord right now lmao.

For the issue of checking if the program is running, you could just reference the PID. Something like:

```cpp
if (memNread == -1 && value == NULL && pid != 0)
    value = 0;
    
else if (memNread == -1 && pid == 0)
    // Throw runtime error
```

If that doesn't work, you could try looking at LiveSplit's code to see how ASL handles NULL values. And if all else  fails, you can try asking in the Speedrun Tools Development Discord.

**Comment by Wins1ey** [comment]
Ideally I'd like to have it not return any value if there isn't one to read. I might implement a way to have the addresses and their values printed out and have them update when they change so you can easily see if there's no value being returned without needing to throw errors.
